- hosts: localhost 
  connection: local
  gather_facts: False
  tasks:
  - name: Clone the template
    vmware_guest:
      validate_certs: no
      name: "{{ hostname }}"
      template: template_centos7
      datacenter: DC1
      folder: '/vm'
      disk:
      - size_gb: 20
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 1024
        num_cpus: 1
        num_cpu_cores_per_socket: 1
      wait_for_ip_address: no
