- hosts: localhost 
  connection: local
  gather_facts: False
  tasks:
  - name: Set the state of a virtual machine to poweroff
    vmware_guest_powerstate:
      hostname: 129.213.140.49
      username: administrator@vsphere.local
      password: "(( password ))"
      validate_certs: no
      name: centservtommy
      folder: "/vm"
      name: "(( guest_name ))"
      state: powered-off
    delegate_to: localhost
    register: deploy
