- hosts: localhost 
  connection: local
  gather_facts: False
  vars_files:
    - vars/main.yml
  tasks:
  - name: Set the state of a virtual machine to poweroff
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: 
      folder: "/DC1/vm"
      name: "{{ guest_name }}"
      state: powered-off
    delegate_to: localhost
    register: deploy
