- hosts: localhost 
  connection: local
  gather_facts: False
  tasks:
  - name: Set the state of a virtual machine to poweroff
    vmware_guest_powerstate:
      hostname: "{{ vcenterserv-napartnerswindowse-thsnxqla.srv.ravcloud.com }}"
      username: "{{ administrator@vsphere.local }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "/vm"
      name: "(( guest_name ))"
      state: powered-off
    delegate_to: localhost
    register: deploy
