- hosts: localhost 
  connection: local
  gather_facts: False
  vars_files:
  - 'vars/main.yml'  
  tasks:
  - name: Set the state of a virtual machine to poweron
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: administrator@vsphere.local
      password: "{{ password }}"
      validate_certs: no
      name: 
      folder: "/DC1/vm"
      name: "{{ hostname }}"
      state: powered-on
    delegate_to: localhost
    register: deploy
